### ISSUE TITLE
tredly start container ?

### ISSUE THREAD

**Issue by cmanns** [tredly/tredly-host#13]
I am testing tredly in vm as I imagine others are

Whenever I start/reboot the tredly-host, containers are down

**Comment by laurieodgers** [comment]
Hi cmanns
Thanks for the ticket.

This has been something we have been discussing for a while; VUID has not needed this functionality thus far as hosts are never shut down, however it would be trivial to implement as the functionality alread exists. Look for it in the next release 0.10.0, or feel free to have a go at implementing it yourself - look in the container.sh file for function container_start()

**Comment by nathanaherne** [comment]
To completely integrate this with Tredly we would need to implement a new variable in the OrderOfOperations section of the Tredlyfile:
1. onCreate (commands run on container create)
2. onStart (commands run on Container start - these would be run on firstStart or reStart)
3. onStop (commands run on Container stop)

If we left things as they were, when a container was restarted you may wish to run commands, which the Tredlyfile could allow.

**Comment by laurieodgers** [comment]
Nathan is correct - this will require more thought than simply running the container_start. 

Some refactoring of code is also required to assign ip addresses within the container_start() function instead of container_create(). 

Since we are in RC1 for 0.10.0 I am going to push this back to 0.11.0.

**Comment by laurieodgers** [comment]
I just wanted to post here to let you know we haven't forgotten about this! 

Starting a pre-made container has turned out to be a lot more work than I had anticipated due to the fact that Tredly was originally designed for all containers to be disposable. 

Rest assured that we have not forgotten about this and it will be available soon!

**Comment by laurieodgers** [comment]
@cmanns this is now working in the vuid_com beta repo of 1.0.0 (see reference above) however I haven't merged in the branch to tredly as I haven't had a chance to fully test the updating of host data on start and stop (such as layer7 proxy/layer 4 proxy/DNS). Plus my code requires a code review from the eagle eye of @pointybeard  :) 

Look for this code in the https://github.com/tredly/tredly (1.0 beta) repo in the next 24 hours. I will also be implementing many more features slated for the 1.0 release in the coming weeks!

**Comment by laurieodgers** [comment]
This feature is now in the latest release of v1.0.0-beta available at https://github.com/tredly/tredly

**Comment by laurieodgers** [comment]
This feature is in the v1.0 release. Closing this ticket.
