### ISSUE TITLE
Not allowed access to API

### ISSUE THREAD

**Issue by dinapappor** [tredly/tredly-host#35]
Hi, with the latest version I am not able to access the API, which is used to push the containers.

Adding the subnet where I will be pushing from to `/usr/local/etc/ipfw.table.20` solves this for me.

**Comment by nathanaherne** [comment]
You may be seeing this because: I do remember asking for the API to be installed but not enabled for security reasons. Not 100% sure if this change made it in but this issue would certainly point towards it making it.

Thinking about this issue further, I think we will go back to enabling it by default and having a random password generated for it on install or something like this to solve the security issue.

**Comment by laurieodgers** [comment]
@nathanaherne is correct - having the API open to the world is a security risk but the functionality to allow whitelisted IPs to connect to it is implemented via ipfw table 20 (/usr/local/etc/ipfw.table.20). 

This has been implemented in preparation for Tredly Command Center, the web interface for Tredly management which will be available soon.

**Comment by dinapappor** [comment]
@laurieodgers How about a managementNet option during the install? Which could ofcourse be a /32, /24 or whatever. Or a list of network/hosts like this: `172.16.0.0./24,10.0.90.55/32`.

**Comment by nathanaherne** [comment]
I think we should open the API by default or come up with a way to manually configure a host pre install as we need to be able to install tredly and have command centre connect to it with minimal intervention.

**Comment by dinapappor** [comment]
For **my** usecase having it open our not does not matter since I run it in a pretty locked down aws VPC enviroment.

One could have it open by default (but really, shouldn't). But also have a `$managementNet` and/or `$tredlyCommandCenter` to optionally enter during install. Since I atleast in **my** usecase - which might of course not apply to other usescases/infrastructure setups, I can do either one this would be the best compromise - IMO.

**Comment by laurieodgers** [comment]
You can whitelist an ip address or range by issuing the command "tredy-host config firewall addAPIwhitelist <your subnet>/<cidr>" which will add that range to the API whitelist (ipfw table 20). This has the same effect as adding the rule manually to /usr/local/etc/ipfw.table.20 and running the same. I haven't tested with 0.0.0.0/0 (allow any) but am interested to hear if it works? (note that the tredly-host command may change as we are unifying everything into a single tredly command)

Whitelisting the API will likely be an option added to the installer in a future release (soon)

**Comment by laurieodgers** [comment]
I am planning on adding the api whitelist option to the installer when we start work tomorrow - expect to see a release of tredly-host incorporating an option to set it in the next 24 hours.

Due to the length of time the installer takes to complete, tomorrow's release also includes a flag in the installer config file to perform an unattended installation. Within this file you can set the same values that are set by the installer menu.
